# Kennel 配置文件

# 全局配置
global:
  # 应用程序基本信息
  app:
    name: "kennel"
    version: "1.0.0"
    description: "跨平台终端代理框架"

  # 日志配置
  logging:
    level: "debug"
    file: "logs/kennel.log"
    format: "json"
    max_size: 10  # MB
    max_backups: 5
    max_age: 30  # 天
    compress: true

  # 系统配置
  system:
    temp_dir: "tmp"
    data_dir: "data"
    pid_file: "kennel.pid"
    graceful_timeout: 30  # 秒

  # Web控制台配置
  web_console:
    enabled: true
    host: "0.0.0.0"
    port: 8088
    enable_https: false
    cert_file: ""
    key_file: ""
    static_dir: "web/dist"
    enable_auth: false
    username: "admin"
    password: "admin"
    rate_limit: 100
    enable_csrf: false
    api_prefix: "/api"
    session_timeout: "24h"
    allow_origins: ["*", "http://localhost:8088", "http://127.0.0.1:8088"]

# 插件管理配置
plugin_manager:
  # 插件目录
  plugin_dir: "plugins"

  # 插件发现
  discovery:
    scan_interval: 60  # 秒
    auto_load: true
    follow_symlinks: false

  # 插件隔离
  isolation:
    default_level: "process"  # none, process, container
    resource_limits:
      cpu: 50  # 百分比
      memory: 100  # MB
      disk: 1000  # MB

  # 插件生命周期
  lifecycle:
    startup_timeout: 30  # 秒
    shutdown_timeout: 30  # 秒
    health_check_interval: 60  # 秒
    auto_restart: true
    max_restarts: 3
    restart_delay: 5  # 秒

# 通讯模块配置
comm:
  server_address: "localhost"
  server_port: 9000
  protocol: "tcp"
  # 设置为false可以禁用通讯功能，避免连接错误
  enabled: false
  timeout: 30
  retry_interval: 5
  max_retries: 3
  keep_alive: true

# 插件管理配置
plugin_manager:
  # 插件目录
  plugin_dir: "plugins"

  # 插件发现
  discovery:
    scan_interval: 60  # 秒
    auto_load: true
    follow_symlinks: false

  # 插件隔离
  isolation:
    default_level: "process"  # none, process, container
    resource_limits:
      cpu: 50  # 百分比
      memory: 100  # MB
      disk: 1000  # MB

  # 插件生命周期
  lifecycle:
    startup_timeout: 30  # 秒
    shutdown_timeout: 30  # 秒
    health_check_interval: 60  # 秒
    auto_restart: true
    max_restarts: 3
    restart_delay: 5  # 秒

# 插件配置
plugins:
  # 资产管理插件
  assets:
    enabled: true
    name: "资产管理插件"
    version: "1.0.0"
    path: "assets"
    auto_start: true
    auto_restart: true
    isolation_level: "none"
    # 插件特定配置
    settings:
      # 收集间隔（秒）
      collect_interval: 3600
      # 上报服务器
      report_server: "https://example.com/api/assets"
      # 是否启用自动上报
      auto_report: false

  # 设备管理插件
  device:
    enabled: true
    name: "设备管理插件"
    version: "1.0.0"
    path: "device"
    auto_start: true
    auto_restart: true
    isolation_level: "none"
    # 插件特定配置
    settings:
      # 是否监控USB设备
      monitor_usb: true
      # 是否监控网络接口
      monitor_network: true
      # 是否允许禁用网络接口
      allow_network_disable: true

  # 数据防泄漏插件
  dlp:
    enabled: true
    name: "数据防泄漏插件"
    version: "1.0.0"
    path: "dlp"
    auto_start: true
    auto_restart: true
    isolation_level: "none"
    # 插件特定配置
    settings:
      # 规则配置
      rules:
        - id: "credit-card"
          name: "信用卡号"
          description: "检测信用卡号"
          pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})\\b"
          action: "alert"
          enabled: true
        - id: "email"
          name: "电子邮件地址"
          description: "检测电子邮件地址"
          pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
          action: "alert"
          enabled: true
        - id: "ip-address"
          name: "IP地址"
          description: "检测IP地址"
          pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
          action: "alert"
          enabled: true
      # 是否启用剪贴板监控
      monitor_clipboard: false
      # 是否启用文件监控
      monitor_files: false
      # 监控的文件类型
      monitored_file_types:
        - "*.doc"
        - "*.docx"
        - "*.xls"
        - "*.xlsx"
        - "*.pdf"
        - "*.txt"

  # 终端管控插件
  control:
    enabled: true
    name: "终端管控插件"
    version: "1.0.0"
    path: "control"
    auto_start: true
    auto_restart: true
    isolation_level: "none"
    # 插件特定配置
    settings:
      # 是否允许远程执行命令
      allow_remote_command: true
      # 是否允许远程安装软件
      allow_software_install: true
      # 是否允许远程终止进程
      allow_process_kill: true
      # 白名单进程（不允许终止）
      protected_processes:
        - "agent.exe"
        - "system"
        - "explorer.exe"
      # AI配置
      ai:
        enabled: true
        model_type: "openai"
        model_name: "gpt-3.5-turbo"
        api_key: "your-api-key-here"
        base_url: ""
        max_tokens: 2000
        temperature: 0.7
        mcp_enabled: true
        mcp_server_addr: "http://localhost:8080"
        mcp_api_key: "your-mcp-api-key-here"

  # 安全审计插件
  audit:
    enabled: true
    name: "安全审计插件"
    version: "1.0.0"
    path: "audit"
    auto_start: true
    auto_restart: true
    isolation_level: "none"
    # 插件特定配置
    settings:
      # 是否记录系统事件
      log_system_events: true
      # 是否记录用户事件
      log_user_events: true
      # 是否记录网络事件
      log_network_events: true
      # 是否记录文件事件
      log_file_events: true
      # 日志保留天数
      log_retention_days: 30
      # 是否启用实时警报
      enable_alerts: false
      # 警报接收者
      alert_recipients:
        - "admin@example.com"
