# AppFramework 配置文件

# 插件目录
plugin_dir: "app"

# 日志配置
log_level: "debug"
log_file: "agent.log"

# Web控制台配置
web_console:
  enabled: true
  host: "0.0.0.0"
  port: 8088
  enable_https: false
  cert_file: ""
  key_file: ""
  enable_auth: false
  username: "admin"
  password: "admin"
  static_dir: "web/dist"
  log_level: "debug"
  rate_limit: 100
  enable_csrf: false
  api_prefix: "/api"
  session_timeout: "24h"
  allow_origins: ["*", "http://localhost:8088", "http://127.0.0.1:8088"]

# 模块启用配置
enable_assets: true
enable_device: true
enable_dlp: true
enable_control: true
enable_audit: true
enable_comm: true

# 通讯模块配置
comm:
  server_address: "localhost"
  server_port: 9000
  protocol: "tcp"
  # 设置为false可以禁用通讯功能，避免连接错误
  enabled: false
  timeout: 30
  retry_interval: 5
  max_retries: 3
  keep_alive: true

# 资产管理模块配置
assets:
  # 收集间隔（秒）
  collect_interval: 3600
  # 上报服务器
  report_server: "https://example.com/api/assets"
  # 是否启用自动上报
  auto_report: false

# 设备管理模块配置
device:
  # 是否监控USB设备
  monitor_usb: true
  # 是否监控网络接口
  monitor_network: true
  # 是否允许禁用网络接口
  allow_network_disable: true

# 数据防泄漏模块配置
dlp:
  # 规则配置
  rules:
    - id: "credit-card"
      name: "信用卡号"
      description: "检测信用卡号"
      pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})\\b"
      action: "alert"
      enabled: true
    - id: "email"
      name: "电子邮件地址"
      description: "检测电子邮件地址"
      pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
      action: "alert"
      enabled: true
    - id: "ip-address"
      name: "IP地址"
      description: "检测IP地址"
      pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
      action: "alert"
      enabled: true
  # 是否启用剪贴板监控
  monitor_clipboard: false
  # 是否启用文件监控
  monitor_files: false
  # 监控的文件类型
  monitored_file_types:
    - "*.doc"
    - "*.docx"
    - "*.xls"
    - "*.xlsx"
    - "*.pdf"
    - "*.txt"

  # OCR配置
  ocr:
    enabled: true
    engine: "tesseract"
    language: "chi_sim+eng"
    timeout: 30
    max_image_size: 10485760  # 10MB
    confidence_threshold: 60
    preprocessing:
      enabled: true
      resize: true
      denoise: true
      contrast: true
    cache:
      enabled: true
      max_size: 100
      ttl: 3600
    performance:
      max_concurrent: 2
      queue_size: 100
      memory_limit: 536870912  # 512MB

  # ML配置
  ml:
    enabled: true
    model_path: "models/dlp_model.tflite"
    confidence_threshold: 0.7
    max_text_length: 10000
    batch_size: 32
    timeout: 10
    cache:
      enabled: true
      max_size: 1000
      ttl: 1800
    performance:
      max_concurrent: 4
      queue_size: 200
      memory_limit: 1073741824  # 1GB

# 终端管控模块配置
control:
  # 是否允许远程执行命令
  allow_remote_command: true
  # 是否允许远程安装软件
  allow_software_install: true
  # 是否允许远程终止进程
  allow_process_kill: true
  # 白名单进程（不允许终止）
  protected_processes:
    - "agent.exe"
    - "system"
    - "explorer.exe"

# 安全审计模块配置
audit:
  # 是否记录系统事件
  log_system_events: true
  # 是否记录用户事件
  log_user_events: true
  # 是否记录网络事件
  log_network_events: true
  # 是否记录文件事件
  log_file_events: true
  # 日志保留天数
  log_retention_days: 30
  # 是否启用实时警报
  enable_alerts: false
  # 警报接收者
  alert_recipients:
    - "admin@example.com"

# 自我防护配置
self_protection:
  # 是否启用自我防护（需要编译时启用selfprotect标签）
  enabled: false
  # 防护级别：none, basic, standard, strict
  level: "basic"
  # 紧急禁用文件（存在此文件时自动禁用防护）
  emergency_disable: ".emergency_disable"
  # 检查间隔
  check_interval: "5s"
  # 重启延迟
  restart_delay: "3s"
  # 最大重启尝试次数
  max_restart_attempts: 3

  # 白名单配置
  whitelist:
    enabled: true
    # 白名单进程
    processes:
      - "taskmgr.exe"
      - "procexp.exe"
      - "procexp64.exe"
    # 白名单用户
    users:
      - "SYSTEM"
      - "Administrator"
    # 白名单签名
    signatures: []

  # 进程防护配置
  process_protection:
    enabled: true
    # 受保护的进程
    protected_processes:
      - "agent.exe"
      - "dlp.exe"
      - "audit.exe"
      - "device.exe"
    # 是否监控子进程
    monitor_children: true
    # 是否防止调试
    prevent_debug: true
    # 是否防止内存转储
    prevent_dump: true

  # 文件防护配置
  file_protection:
    enabled: true
    # 受保护的文件
    protected_files:
      - "config.yaml"
      - "agent.exe"
    # 受保护的目录
    protected_dirs:
      - "app"
    # 是否检查文件完整性
    check_integrity: true
    # 是否启用备份
    backup_enabled: true
    # 备份目录
    backup_dir: "backup"

  # 注册表防护配置（仅Windows）
  registry_protection:
    enabled: true
    # 受保护的注册表键
    protected_keys:
      - "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\KennelAgent"
    # 是否监控注册表变更
    monitor_changes: true

  # 服务防护配置（仅Windows）
  service_protection:
    enabled: true
    # 服务名称
    service_name: "KennelAgent"
    # 是否自动重启
    auto_restart: true
    # 是否防止禁用
    prevent_disable: true
