# 数据防泄漏插件配置
enabled: true

# 是否启用剪贴板监控
monitor_clipboard: false

# 是否启用文件监控
monitor_files: false

# 监控的文件类型
monitored_file_types:
  - "*.doc"
  - "*.docx"
  - "*.xls"
  - "*.xlsx"
  - "*.pdf"
  - "*.txt"

# 监控的目录
monitored_directories:
  - "C:/Users/*/Documents"
  - "C:/Users/*/Desktop"

# 日志级别
log_level: "info"

# 规则配置
rules:
  - id: "credit-card"
    name: "信用卡号"
    description: "检测信用卡号"
    pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})\\b"
    action: "alert"
    enabled: true
  
  - id: "email"
    name: "电子邮件地址"
    description: "检测电子邮件地址"
    pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
    action: "alert"
    enabled: true
  
  - id: "ip-address"
    name: "IP地址"
    description: "检测IP地址"
    pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    action: "alert"
    enabled: true
