# DLP模块性能优化配置
name: "dlp"
version: "2.0.0"
description: "数据防泄漏插件 - 性能优化版本"

# 基础功能开关
monitor_network: true
monitor_files: true
monitor_clipboard: true

# 性能优化配置
max_concurrency: 4        # 最大并发处理数（减少CPU占用）
buffer_size: 500          # 缓冲区大小（减少内存占用）

# 网络监控配置
network_protocols:
  - "http"
  - "https"
  - "ftp"
  - "smtp"

# 拦截器性能配置 - 已优化排除私有网络流量
interceptor_config:
  # 注意：实际过滤器由代码动态生成，会自动排除私有网络流量
  # 这个filter配置项已被buildOptimizedFilter()方法覆盖
  filter: "outbound and (tcp.DstPort == 80 or tcp.DstPort == 443 or tcp.DstPort == 21 or tcp.DstPort == 25 or tcp.DstPort == 3306)"
  buffer_size: 32768       # 32KB缓冲区
  channel_size: 500        # 通道大小
  priority: 0
  flags: 1                 # WINDIVERT_FLAG_SNIFF - 嗅探模式，不阻断流量
  queue_len: 4096          # WinDivert队列长度
  queue_time: 1000         # WinDivert队列时间(ms)
  worker_count: 2          # 工作协程数
  cache_size: 500          # 进程缓存大小
  interface: "en0"
  # 绕过本地和私有网络流量（已在WinDivert过滤器层面实现）
  bypass_cidr: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  proxy_port: 8080
  mode: 0                  # 0=监控模式, 1=拦截并允许, 2=拦截并阻断
  auto_reinject: true      # 自动重新注入数据包

# 白名单配置
whitelist:
  enable: true             # 启用白名单
  processes:               # 进程白名单
    - "opera.exe"
    - "dlp.exe"
  domains:                 # 域名白名单
    - "*.google.com"
    - "*.microsoft.com"
    - "*.github.com"
    - "*.stackoverflow.com"
    - "localhost"
    - "127.0.0.1"
  ips:                     # IP白名单
    - "127.0.0.0/8"        # 本地回环
    - "10.0.0.0/8"         # 私有网络A类
    - "172.16.0.0/12"      # 私有网络B类
    - "192.168.0.0/16"     # 私有网络C类
    - "169.254.0.0/16"     # 链路本地地址

# 解析器配置
parser_config:
  max_parsers: 6           # 最大解析器数量
  timeout: 5000            # 解析超时时间(ms)

# 分析器配置
analyzer_config:
  max_analyzers: 3         # 最大分析器数量
  timeout: 3000            # 分析超时时间(ms)

# 策略引擎配置
engine_config:
  max_rules: 100           # 最大规则数量
  evaluation_timeout: 2000 # 策略评估超时时间(ms)

# 执行器配置
executor_config:
  max_executors: 5         # 最大执行器数量
  action_timeout: 1000     # 动作执行超时时间(ms)

# 文件监控配置
monitored_directories:
  - "C:\\Users\\%USERNAME%\\Documents"
  - "C:\\Users\\%USERNAME%\\Desktop"
  - "C:\\Users\\%USERNAME%\\Downloads"

monitored_file_types:
  - ".txt"
  - ".doc"
  - ".docx"
  - ".pdf"
  - ".xls"
  - ".xlsx"

# 日志配置
logging:
  level: "info"            # 减少日志级别，提高性能
  format: "json"
  output: "stdout"

# 性能监控配置
performance:
  enable_metrics: true     # 启用性能指标
  stats_interval: 300      # 统计间隔(秒)
  memory_limit: 512        # 内存限制(MB)
  cpu_limit: 50            # CPU使用率限制(%)

# 自适应性能调整
adaptive:
  enable: true             # 启用自适应调整
  check_interval: 60       # 检查间隔(秒)
  cpu_threshold: 80        # CPU阈值(%)
  memory_threshold: 80     # 内存阈值(%)

# 流量限制配置
traffic_limit:
  enable: true             # 启用流量限制
  max_packets_per_second: 1000  # 每秒最大数据包数
  max_bytes_per_second: 10485760  # 每秒最大字节数(10MB)
  burst_size: 100          # 突发大小

# 优先级配置
priority:
  high_priority_ports:     # 高优先级端口
    - 443                  # HTTPS
    - 80                   # HTTP
  low_priority_ports:      # 低优先级端口
    - 21                   # FTP
    - 25                   # SMTP
    - 3306                 # MySQL

# OCR（光学字符识别）配置
ocr:
  # 是否启用OCR功能
  enabled: true

  # OCR引擎类型 (tesseract)
  engine: "tesseract"

  # Tesseract配置
  tesseract:
    # 支持的语言包 (eng=英文, chi_sim=简体中文, chi_tra=繁体中文)
    languages:
      - "eng"
      - "chi_sim"

    # 处理超时时间（秒）
    timeout_seconds: 30

    # 最大图像大小（字节）
    max_image_size: 10485760  # 10MB

    # 是否启用图像预处理
    enable_preprocessing: true

    # Tesseract可执行文件路径（可选，留空则使用系统PATH）
    tesseract_path: ""

    # Tesseract数据目录路径（可选）
    tessdata_prefix: ""

    # OCR引擎模式
    # 0 = 仅OCR
    # 1 = 自动页面分割和OCR
    # 2 = 自动页面分割，但不进行OCR或OSD
    # 3 = 完全自动页面分割，但不进行OSD
    engine_mode: 1

    # 页面分割模式
    # 0 = 仅方向和脚本检测(OSD)
    # 1 = 带OSD的自动页面分割
    # 3 = 完全自动页面分割，但不进行OSD
    # 6 = 统一的文本块
    # 7 = 将图像视为单个文本行
    # 8 = 将图像视为单个单词
    # 13 = 将图像视为单个字符
    page_seg_mode: 3

    # 字符白名单（可选，限制识别的字符）
    char_whitelist: ""

    # 字符黑名单（可选，排除的字符）
    char_blacklist: ""

# 机器学习配置
ml:
  # 是否启用ML功能
  enabled: true

  # ML模型类型
  model_type: "simple"

  # 简单模型配置
  simple_model:
    # 敏感关键词
    sensitive_keywords:
      - "password"
      - "密码"
      - "身份证"
      - "信用卡"
      - "银行卡"
      - "secret"
      - "confidential"
      - "机密"
      - "内部"
      - "token"
      - "api_key"
      - "private_key"

    # 置信度阈值
    confidence_threshold: 0.7

    # 风险评分阈值
    risk_threshold: 0.5

# 文件类型检测配置
file_detection:
  # 是否启用文件类型检测
  enabled: true

  # 支持的图像格式
  supported_image_formats:
    - "image/jpeg"
    - "image/png"
    - "image/tiff"
    - "image/bmp"
    - "image/gif"
    - "image/webp"

  # 支持的文档格式
  supported_document_formats:
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    - "text/plain"
    - "text/csv"
    - "text/html"

# OCR性能配置
ocr_performance:
  # 最大并发OCR任务数
  max_concurrent_ocr: 3

  # OCR任务队列大小
  ocr_queue_size: 100

  # 缓存配置
  cache:
    # 是否启用缓存
    enabled: true

    # 缓存大小（条目数）
    max_entries: 1000

    # 缓存TTL（秒）
    ttl_seconds: 3600

# OCR日志配置
ocr_logging:
  # OCR日志级别
  ocr_log_level: "info"

  # 是否记录OCR处理时间
  log_processing_time: true

  # 是否记录识别的文本长度
  log_text_length: true

  # 是否记录错误详情
  log_error_details: true

# 规则配置
rules:
  # 敏感信息检测规则
  sensitive_data:
    - name: "身份证号检测"
      type: "regex"
      pattern: "[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]"
      risk_level: "high"
      action: "alert"
      enabled: true

    - name: "手机号检测"
      type: "regex"
      pattern: "1[3-9]\\d{9}"
      risk_level: "medium"
      action: "audit"
      enabled: true

    - name: "邮箱地址检测"
      type: "regex"
      pattern: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
      risk_level: "low"
      action: "audit"
      enabled: true

    - name: "信用卡号检测"
      type: "regex"
      pattern: "\\b(?:\\d{4}[-\\s]?){3}\\d{4}\\b"
      risk_level: "high"
      action: "block"
      enabled: true

  # 关键词检测规则
  keywords:
    - name: "机密文档关键词"
      keywords: ["机密", "绝密", "内部", "保密", "confidential", "secret", "internal"]
      risk_level: "high"
      action: "alert"
      case_sensitive: false
      whole_word: true
      enabled: true

    - name: "密码相关关键词"
      keywords: ["password", "passwd", "pwd", "密码", "口令"]
      risk_level: "medium"
      action: "audit"
      case_sensitive: false
      whole_word: true
      enabled: true

# 告警配置
alerts:
  channels:
    - type: "email"
      enabled: false
      config:
        smtp_server: "smtp.example.com"
        smtp_port: 587
        username: "alert@example.com"
        password: "password"
        recipients: ["admin@example.com"]

    - type: "webhook"
      enabled: false
      config:
        url: "https://hooks.example.com/dlp-alerts"
        method: "POST"

# 审计配置
audit:
  enabled: true
  log_path: "logs/dlp_audit.log"
  max_size: 104857600  # 100MB
  max_age: 30  # 30天
  max_backups: 10
  compress: true
