# 终端管控插件V2配置文件

# 基本配置
id: control
name: 终端管控插件
version: 2.0.0
enabled: true
log_level: info

# 运行时配置
auto_start: true
auto_restart: true

# 隔离配置
isolation:
  level: basic
  resources:
    memory: 256000000  # 256MB
    cpu: 50            # 50% CPU
  timeout: 30s
  working_dir: ./data
  environment:
    DEBUG: "false"
    PLUGIN_MODE: "production"

# 插件特定配置
settings:
  # 进程管理配置
  process:
    max_processes: 1000
    refresh_interval: 5s
    allow_kill: true
    protected_processes:
      - system
      - wininit
      - services
      - lsass

  # 命令执行配置
  command:
    timeout: 60s
    max_output_size: 10485760  # 10MB
    allowed_commands:
      - cmd.exe
      - powershell.exe
      - wmic
    blocked_commands:
      - format
      - fdisk
      - diskpart

  # AI配置
  ai:
    enabled: true
    provider: openai
    model: gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 2000
    timeout: 30s
    providers:
      openai:
        api_key: ${OPENAI_API_KEY}
        organization: ${OPENAI_ORG_ID}
        base_url: https://api.openai.com/v1
      ark:
        api_key: ${ARK_API_KEY}
        base_url: https://api.ark-model.com/v1
      eino:
        server_address: localhost:8080
        timeout: 10s
        tls_enabled: false
        cert_file: ""
        key_file: ""
        ca_file: ""

  # 安全配置
  security:
    require_authentication: true
    require_authorization: true
    audit_logging: true
    encryption:
      enabled: true
      algorithm: AES-256-GCM
      key_rotation_interval: 168h  # 7 days

  # 网络配置
  network:
    listen_address: 0.0.0.0
    port: 8081
    tls:
      enabled: true
      cert_file: ./certs/server.crt
      key_file: ./certs/server.key
    rate_limit:
      enabled: true
      requests_per_minute: 60
      burst: 10

  # 监控配置
  monitoring:
    enabled: true
    metrics_interval: 10s
    health_check_interval: 30s
    export_metrics: true
    prometheus:
      enabled: true
      path: /metrics
